### ISSUE TITLE
No module named 'users'

### ISSUE THREAD

**Issue by Elpharz** [howtographql/howtographql#1004]
Help wanted, am following the graphql tutorial but i seem to be running in an issue with ,
here is my log
Django version 2.2.4, using settings 'graphplay.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\views\generic\base.py", line 62, in view
    self = cls(**initkwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\views.py", line 78, in __init__
    schema = graphene_settings.SCHEMA
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 116, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 55, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 69, in import_from_string
    module = importlib.import_module(module_path)
  File "C:\Users\Harvy\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Harvy\PycharmProjects\graphplay\hackergraph\schema.py", line 18, in <module>
    schema = graphene.Schema(users.schema.Mutation, query=Query, mutation=Mutation)
NameError: name 'users' is not defined
[19/Aug/2019 14:43:16] "GET /graphql/ HTTP/1.1" 500 123484
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\views\generic\base.py", line 62, in view
    self = cls(**initkwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\views.py", line 78, in __init__
    schema = graphene_settings.SCHEMA
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 116, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 55, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 69, in import_from_string
    module = importlib.import_module(module_path)
  File "C:\Users\Harvy\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Harvy\PycharmProjects\graphplay\hackergraph\schema.py", line 18, in <module>
    schema = graphene.Schema(hackergraph.users.schema.Mutation, query=Query, mutation=Mutation)
TypeError: __init__() got multiple values for argument 'query'
[19/Aug/2019 14:45:20] "GET /graphql/ HTTP/1.1" 500 123885
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\views\generic\base.py", line 62, in view
    self = cls(**initkwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\views.py", line 78, in __init__
    schema = graphene_settings.SCHEMA
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 116, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 55, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 69, in import_from_string
    module = importlib.import_module(module_path)
  File "C:\Users\Harvy\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Harvy\PycharmProjects\graphplay\hackergraph\schema.py", line 18, in <module>
    schema = graphene.Schema(users.schema.Mutation, query=Query, mutation=Mutation)
NameError: name 'users' is not defined
[19/Aug/2019 14:46:41] "GET /graphql/ HTTP/1.1" 500 123765
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 69, in import_from_string
    module = importlib.import_module(module_path)
  File "C:\Users\Harvy\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Harvy\PycharmProjects\graphplay\hackergraph\schema.py", line 4, in <module>
    import users.schema
ModuleNotFoundError: No module named 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\views\generic\base.py", line 62, in view
    self = cls(**initkwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\views.py", line 78, in __init__
    schema = graphene_settings.SCHEMA
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 116, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 55, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 78, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'hackergraph.schema.schema' for Graphene setting 'SCHEMA'. ModuleNotFoundError: No module named 'users'.
[19/Aug/2019 14:48:37] "GET /graphql/ HTTP/1.1" 500 128655

(graphenv) C:\Users\Harvy\PycharmProjects\graphplay>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 19, 2019 - 14:54:49
Django version 2.2.4, using settings 'graphplay.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 69, in import_from_string
    module = importlib.import_module(module_path)
  File "C:\Users\Harvy\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Harvy\PycharmProjects\graphplay\hackergraph\schema.py", line 4, in <module>
    import users.schema
ModuleNotFoundError: No module named 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\django\views\generic\base.py", line 62, in view
    self = cls(**initkwargs)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\views.py", line 78, in __init__
    schema = graphene_settings.SCHEMA
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 116, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 55, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\Harvy\PycharmProjects\graphplay\graphenv\lib\site-packages\graphene_django\settings.py", line 78, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'hackergraph.schema.schema' for Graphene setting 'SCHEMA'. ModuleNotFoundError: No module named 'users'.
[19/Aug/2019 14:55:02] "GET /graphql/ HTTP/1.1" 500 128655

**Comment by Denniskamau** [comment]
From the tutorial it is written that in the `hackernews/schema.py` we import `import users.schema` and I think this might be the problem.
Try importing the `user schema` this way instead `from .users import schema` and reference it in both  the `Query` and `Mutation` class as `schema.Query` and `schema.Mutation`

**Comment by kiuru** [comment]
> From the tutorial it is written that in the `hackernews/schema.py` we import `import users.schema` and I think this might be the problem.
> Try importing the `user schema` this way instead `from .users import schema` and reference it in both the `Query` and `Mutation` class as `schema.Query` and `schema.Mutation`

This solved my issue!

**Comment by itofficeeu** [comment]
Is this issue ready to be closed?...
