### ISSUE TITLE
Tutorial "react-apollo/1-getting-started" broken at "prisma deploy"

### ISSUE THREAD

**Issue by itofficeeu** [howtographql/howtographql#1046]
Following the tutorial, ends in a not working state.

The problem arises when using the command "prisma deploy" for the first time.

https://www.howtographql.com/react-apollo/1-getting-started/

https://github.com/howtographql/howtographql/blob/master/content/frontend/react-apollo/1-getting-started.md

Section: Backend
Subsection: Deploying the Prisma database service

The commands 

```
cd server
npm install
prisma deploy
```
(I use npm instead of yarn)

results in

```
server$ prisma deploy
  command Failed to get the server +0ms
  Environment undefined +0ms
  environment FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466
  environment     at ClientRequest.<anonymous> (/usr/lib/node_modules/prisma/node_modules/node-fetch/lib/index.js:1393:11)
  environment     at emitOne (events.js:116:13)
  environment     at ClientRequest.emit (events.js:211:7)
  environment     at Socket.socketErrorListener (_http_client.js:401:9)
  environment     at emitOne (events.js:116:13)
  environment     at Socket.emit (events.js:211:7)
  environment     at emitErrorNT (internal/streams/destroy.js:73:8)
  environment     at _combinedTickCallback (internal/process/next_tick.js:139:11)
  environment     at process._tickDomainCallback (internal/process/next_tick.js:219:9) +0ms
  environment FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466
  environment     at ClientRequest.<anonymous> (/usr/lib/node_modules/prisma/node_modules/node-fetch/lib/index.js:1393:11)
  environment     at emitOne (events.js:116:13)
  environment     at ClientRequest.emit (events.js:211:7)
  environment     at Socket.socketErrorListener (_http_client.js:401:9)
  environment     at emitOne (events.js:116:13)
  environment     at Socket.emit (events.js:211:7)
  environment     at emitErrorNT (internal/streams/destroy.js:73:8)
  environment     at _combinedTickCallback (internal/process/next_tick.js:139:11)
  environment     at process._tickDomainCallback (internal/process/next_tick.js:219:9) +3ms
  client Sending query to cloud api +0ms
  client https://api2.cloud.prisma.sh +0ms
  client {
  client       me {
  client         id
  client         name
  client         login {
  client           email
  client         }
  client       }
  client     } +0ms
  client undefined +0ms
  client { headers: 
  client    { Authorization: 'Bearer <REMOVED BY PURPOSE> },
  client   agent: undefined } +1ms
? Set up a new Prisma server or deploy to an existing server? Create new database
? What kind of database do you want to deploy to? MySQL
  client Sending query to cluster local +42s
  client http://localhost:4466/management +0ms
  client 
  client       query($name: String! $stage: String!) {
  client         project(name: $name stage: $stage) {
  client           name
  client           stage
  client         }
  client       }
  client      +0ms
  client { name: 'default', stage: 'default' } +0ms
  client Sending query to cluster local +1ms
  client http://localhost:4466/management +0ms
  client 
  client       query($name: String! $stage: String!) {
  client         project(name: $name stage: $stage) {
  client           name
  client           stage
  client         }
  client       }
  client      +0ms
  client { name: 'default', stage: 'default' } +0ms

Written endpoint `http://localhost:4466` to prisma.yml

  environment FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466
  environment     at ClientRequest.<anonymous> (/usr/lib/node_modules/prisma/node_modules/node-fetch/lib/index.js:1393:11)
  environment     at emitOne (events.js:116:13)
  environment     at ClientRequest.emit (events.js:211:7)
  environment     at Socket.socketErrorListener (_http_client.js:401:9)
  environment     at emitOne (events.js:116:13)
  environment     at Socket.emit (events.js:211:7)
  environment     at emitErrorNT (internal/streams/destroy.js:73:8)
  environment     at _combinedTickCallback (internal/process/next_tick.js:139:11)
  environment     at process._tickDomainCallback (internal/process/next_tick.js:219:9) +42s
  environment FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466
  environment     at ClientRequest.<anonymous> (/usr/lib/node_modules/prisma/node_modules/node-fetch/lib/index.js:1393:11)
  environment     at emitOne (events.js:116:13)
  environment     at ClientRequest.emit (events.js:211:7)
  environment     at Socket.socketErrorListener (_http_client.js:401:9)
  environment     at emitOne (events.js:116:13)
  environment     at Socket.emit (events.js:211:7)
  environment     at emitErrorNT (internal/streams/destroy.js:73:8)
  environment     at _combinedTickCallback (internal/process/next_tick.js:139:11)
  environment     at process._tickDomainCallback (internal/process/next_tick.js:219:9) +2ms
Error: Could not connect to server at http://localhost:4466. Please check if your server is running.
    at Deploy.<anonymous> (/usr/lib/node_modules/prisma/node_modules/prisma-cli-core/src/commands/deploy/deploy.ts:137:13)
    at step (/usr/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:45:23)
    at Object.next (/usr/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:26:53)
    at fulfilled (/usr/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:17:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  output Exiting with code: 1 +0ms
server$ 
```

I have checked the file

server/src/generated/prisma-client/index.js

and ensured that the endpoint was set. (I can't remember if I had to set it there).

Even with the endpoint set in that file, does prisma deploy go wrong:

```

server$ prisma deploy
  environment FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466
  environment     at ClientRequest.<anonymous> (/usr/lib/node_modules/prisma/node_modules/node-fetch/lib/index.js:1393:11)
  environment     at emitOne (events.js:116:13)
  environment     at ClientRequest.emit (events.js:211:7)
  environment     at Socket.socketErrorListener (_http_client.js:401:9)
  environment     at emitOne (events.js:116:13)
  environment     at Socket.emit (events.js:211:7)
  environment     at emitErrorNT (internal/streams/destroy.js:73:8)
  environment     at _combinedTickCallback (internal/process/next_tick.js:139:11)
  environment     at process._tickDomainCallback (internal/process/next_tick.js:219:9) +0ms
  environment FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466
  environment     at ClientRequest.<anonymous> (/usr/lib/node_modules/prisma/node_modules/node-fetch/lib/index.js:1393:11)
  environment     at emitOne (events.js:116:13)
  environment     at ClientRequest.emit (events.js:211:7)
  environment     at Socket.socketErrorListener (_http_client.js:401:9)
  environment     at emitOne (events.js:116:13)
  environment     at Socket.emit (events.js:211:7)
  environment     at emitErrorNT (internal/streams/destroy.js:73:8)
  environment     at _combinedTickCallback (internal/process/next_tick.js:139:11)
  environment     at process._tickDomainCallback (internal/process/next_tick.js:219:9) +5ms
  command Failed to fetch server version +0ms
  command TypeError: Cannot read property 'replace' of null +0ms
  environment FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466
  environment     at ClientRequest.<anonymous> (/usr/lib/node_modules/prisma/node_modules/node-fetch/lib/index.js:1393:11)
  environment     at emitOne (events.js:116:13)
  environment     at ClientRequest.emit (events.js:211:7)
  environment     at Socket.socketErrorListener (_http_client.js:401:9)
  environment     at emitOne (events.js:116:13)
  environment     at Socket.emit (events.js:211:7)
  environment     at emitErrorNT (internal/streams/destroy.js:73:8)
  environment     at _combinedTickCallback (internal/process/next_tick.js:139:11)
  environment     at process._tickDomainCallback (internal/process/next_tick.js:219:9) +5ms
  environment FetchError: request to http://localhost:4466/management failed, reason: connect ECONNREFUSED 127.0.0.1:4466
  environment     at ClientRequest.<anonymous> (/usr/lib/node_modules/prisma/node_modules/node-fetch/lib/index.js:1393:11)
  environment     at emitOne (events.js:116:13)
  environment     at ClientRequest.emit (events.js:211:7)
  environment     at Socket.socketErrorListener (_http_client.js:401:9)
  environment     at emitOne (events.js:116:13)
  environment     at Socket.emit (events.js:211:7)
  environment     at emitErrorNT (internal/streams/destroy.js:73:8)
  environment     at _combinedTickCallback (internal/process/next_tick.js:139:11)
  environment     at process._tickDomainCallback (internal/process/next_tick.js:219:9) +1ms
Error: Could not connect to server at http://localhost:4466. Please check if your server is running.
    at Deploy.<anonymous> (/usr/lib/node_modules/prisma/node_modules/prisma-cli-core/src/commands/deploy/deploy.ts:137:13)
    at step (/usr/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:45:23)
    at Object.next (/usr/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:26:53)
    at fulfilled (/usr/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/deploy.js:17:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  output Exiting with code: 1 +0ms
server$ 
```

I can start the server with this command:
```
server$ npm start

> hackernews-node@1.0.0 start /*/*/*/*/server
> node src/index.js

  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +3ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +1ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/home/d/d/ub/server/views' +1ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +18ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +0ms
  express:router use '/' corsMiddleware +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +1ms
  express:router:route post '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +0ms
Server is running on http://localhost:4000
```

But - in the Playground - running the command

```
mutation CreatePrismaLink {
  post(
    description: "Prisma turns your database into a GraphQL API 😎",
    url: "https://www.prismagraphql.com"
  ) {
    id
  }
}
```

Only yields

```
{
  "data": null,
  "errors": [
    {
      "message": "request to http://localhost:4466/ failed, reason: connect ECONNREFUSED 127.0.0.1:4466",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "post"
      ]
    }
  ]
}
```

The backend says:
```
(blablabla)

FetchError: request to http://localhost:4466/ failed, reason: connect ECONNREFUSED 127.0.0.1:4466
    at ClientRequest.<anonymous> (/home/d/d/ub/server/node_modules/node-fetch/lib/index.js:1393:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

(blablabla)
```

The file

server/src/generated/prisma-client/index.js

has the following content:

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var prisma_lib_1 = require("prisma-client-lib");
var typeDefs = require("./prisma-schema").typeDefs;

var models = [
  {
    name: "Link",
    embedded: false
  },
  {
    name: "User",
    embedded: false
  },
  {
    name: "Vote",
    embedded: false
  }
];
exports.Prisma = prisma_lib_1.makePrismaClientClass({
  typeDefs,
  models,
  endpoint: `http://localhost:4466`
});
exports.prisma = new exports.Prisma();
```

What to do?....
How to get the tut running again?
Is this a challenge by purpose?

**Comment by itofficeeu** [comment]
I have now done a 
```
prisma init
```

Where I can select what type of Docker - or not. Like the tut states, but never comes up following the tut.

I guess the prisma init has to be performed just before the prisma deploy. And in between those two also a docker-compose up -d plus some 'wait states'.

So the three lines must be five+:

```
cd server
npm install
prisma init
docker-compose up -d

(WAIT SOME TIME - Probe with docker ps until the containers are stable, alias not restarting anymore))

prisma deploy
```

The terminal I have doing the docker-compose up -d:
```
server$ docker-compose up -d
Creating network "server_default" with the default driver
Creating volume "server_mysql" with default driver
Creating server_prisma_1 ... done
Creating server_mysql_1  ... done
server$ 
```

prisma deploy now returns:
```
server$ prisma deploy
  environment { needsAuth: false } +0ms
  client is local cluster: true +0ms
  client Sending query to cloud api +1ms
  client https://api2.cloud.prisma.sh +0ms
  client {
  client       me {
  client         id
  client         name
  client         login {
  client           email
  client         }
  client       }
  client     } +0ms
  client undefined +1ms
  client { headers: 
  client    { Authorization: 'Bearer <REMOVED BY PURPOSE>' },
  client   agent: undefined } +0ms
  deploy checking if project exists +0ms
  client Sending query to cluster local +239ms
  client http://localhost:4466/management +1ms
  client 
  client       query($name: String! $stage: String!) {
  client         project(name: $name stage: $stage) {
  client           name
  client           stage
  client         }
  client       }
  client      +0ms
  client { name: 'default', stage: 'default' } +0ms
  deploy adding project +113ms

Creating stage default for service default...  client Sending query to cluster local +112ms
  client http://localhost:4466/management +0ms
  client       mutation addProject($name: String! $stage: String! $secrets: [String!]) {
  client         addProject(input: {
  client           name: $name,
  client           stage: $stage
  client           secrets: $secrets
  client         }) {
  client           project {
  client             name
  client           }
  client         }
  client       }
  client        +0ms
  client { name: 'default', stage: 'default', secrets: null } +0ms
  client { addProject: { project: { name: 'default' } } } +338ms
 ✔

Deploying service `default` to stage `default` to server `local`...  client Sending query to cluster local +4ms
  client http://localhost:4466/management +0ms
  client 
  client query IntrospectionQuery {
  client   __schema {
  client     queryType { name }
  client     mutationType { name }
  client     subscriptionType { name }
  client     types {
  client       ...FullType
  client     }
  client     directives {
  client       name
  client       description
  client       locations
  client       args {
  client         ...InputValue
  client       }
  client     }
  client   }
  client }
  client 
  client fragment FullType on __Type {
  client   kind
  client   name
  client   description
  client   fields(includeDeprecated: true) {
  client     name
  client     description
  client     args {
  client       ...InputValue
  client     }
  client     type {
  client       ...TypeRef
  client     }
  client     isDeprecated
  client     deprecationReason
  client   }
  client   inputFields {
  client     ...InputValue
  client   }
  client   interfaces {
  client     ...TypeRef
  client   }
  client   enumValues(includeDeprecated: true) {
  client     name
  client     description
  client     isDeprecated
  client     deprecationReason
  client   }
  client   possibleTypes {
  client     ...TypeRef
  client   }
  client }
  client 
  client fragment InputValue on __InputValue {
  client   name
  client   description
  client   type { ...TypeRef }
  client   defaultValue
  client }
  client 
  client fragment TypeRef on __Type {
  client   kind
  client   name
  client   ofType {
  client     kind
  client     name
  client     ofType {
  client       kind
  client       name
  client       ofType {
  client         kind
  client         name
  client         ofType {
  client           kind
  client           name
  client           ofType {
  client             kind
  client             name
  client             ofType {
  client               kind
  client               name
  client               ofType {
  client                 kind
  client                 name
  client               }
  client             }
  client           }
  client         }
  client       }
  client     }
  client   }
  client }
  client  +0ms
  client undefined +1ms
  client { __schema: 
  client    { directives: [ [Object], [Object], [Object] ],
  client      mutationType: { name: 'Mutation' },
  client      subscriptionType: null,
  client      queryType: { name: 'Query' },
  client      types: 
  client       [ [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object],
  client         [Object] ] } } +310ms
  client Sending query to cluster local +2ms
  client http://localhost:4466/management +0ms
  client       mutation($name: String!, $stage: String! $types: String! $dryRun: Boolean $secrets: [String!], $subscriptions: [FunctionInput!], $force: Boolean) {
  client         deploy(input: {
  client           name: $name
  client           stage: $stage
  client           types: $types
  client           dryRun: $dryRun
  client           secrets: $secrets
  client           subscriptions: $subscriptions
  client           force: $force
  client           
  client         }) {
  client           errors {
  client             type
  client             field
  client             description
  client           }
  client           warnings {
  client             type
  client             field
  client             description
  client           }
  client           migration {
  client             ...MigrationFragment
  client           }
  client           
  client           steps { 
  client   type
  client   __typename
  client   ... on CreateEnum {
  client     name
  client     ce_values: values
  client   }
  client   ... on CreateField {
  client     model
  client     name
  client     cf_typeName: typeName
  client     cf_isRequired: isRequired
  client     cf_isList: isList
  client     cf_isUnique: unique
  client     cf_relation: relation
  client     cf_defaultValue: default
  client     cf_enum: enum
  client   }
  client   ... on CreateModel {
  client     name
  client   }
  client   ... on CreateRelation {
  client     name
  client     leftModel
  client     rightModel
  client     after { 
  client   type
  client   ... on Inline {
  client     model
  client     column
  client   }
  client 
  client   ... on LinkTable {
  client     table
  client     modelAColumn
  client     modelBColumn
  client     idColumn
  client     type
  client   }
  client  }
  client   }
  client   
  client     ... on UpdateRelation {
  client       ur_name: name
  client       ur_newName: newName
  client       before { 
  client   type
  client   ... on Inline {
  client     model
  client     column
  client   }
  client 
  client   ... on LinkTable {
  client     table
  client     modelAColumn
  client     modelBColumn
  client     idColumn
  client     type
  client   }
  client  }
  client       ur_after: after { 
  client   type
  client   ... on Inline {
  client     model
  client     column
  client   }
  client 
  client   ... on LinkTable {
  client     table
  client     modelAColumn
  client     modelBColumn
  client     idColumn
  client     type
  client   }
  client  }
  client     }
  client   
  client   ... on DeleteEnum {
  client     name
  client   }
  client   ... on DeleteField {
  client     model
  client     name
  client   }
  client   ... on DeleteModel {
  client     name
  client   }
  client   ... on DeleteRelation {
  client     name
  client   }
  client   ... on UpdateEnum {
  client     name
  client     newName
  client     values
  client   }
  client   ... on UpdateField {
  client     model
  client     name
  client     newName
  client     typeName
  client     isRequired
  client     isList
  client     isUnique: unique
  client     relation
  client     default
  client     enum
  client   }
  client   ... on UpdateModel {
  client     name
  client     um_newName: newName
  client   }
  client  }
  client         }
  client       }
  client       
  client   fragment MigrationFragment on Migration {
  client     revision
  client     steps {
  client       
  client   type
  client   __typename
  client   ... on CreateEnum {
  client     name
  client     ce_values: values
  client   }
  client   ... on CreateField {
  client     model
  client     name
  client     cf_typeName: typeName
  client     cf_isRequired: isRequired
  client     cf_isList: isList
  client     cf_isUnique: unique
  client     cf_relation: relation
  client     cf_defaultValue: default
  client     cf_enum: enum
  client   }
  client   ... on CreateModel {
  client     name
  client   }
  client   ... on CreateRelation {
  client     name
  client     leftModel
  client     rightModel
  client     after { 
  client   type
  client   ... on Inline {
  client     model
  client     column
  client   }
  client 
  client   ... on LinkTable {
  client     table
  client     modelAColumn
  client     modelBColumn
  client     idColumn
  client     type
  client   }
  client  }
  client   }
  client   
  client     ... on UpdateRelation {
  client       ur_name: name
  client       ur_newName: newName
  client       before { 
  client   type
  client   ... on Inline {
  client     model
  client     column
  client   }
  client 
  client   ... on LinkTable {
  client     table
  client     modelAColumn
  client     modelBColumn
  client     idColumn
  client     type
  client   }
  client  }
  client       ur_after: after { 
  client   type
  client   ... on Inline {
  client     model
  client     column
  client   }
  client 
  client   ... on LinkTable {
  client     table
  client     modelAColumn
  client     modelBColumn
  client     idColumn
  client     type
  client   }
  client  }
  client     }
  client   
  client   ... on DeleteEnum {
  client     name
  client   }
  client   ... on DeleteField {
  client     model
  client     name
  client   }
  client   ... on DeleteModel {
  client     name
  client   }
  client   ... on DeleteRelation {
  client     name
  client   }
  client   ... on UpdateEnum {
  client     name
  client     newName
  client     values
  client   }
  client   ... on UpdateField {
  client     model
  client     name
  client     newName
  client     typeName
  client     isRequired
  client     isList
  client     isUnique: unique
  client     relation
  client     default
  client     enum
  client   }
  client   ... on UpdateModel {
  client     name
  client     um_newName: newName
  client   }
  client 
  client     }
  client   }
  client 
  client      +0ms
  client { name: 'default',
  client   stage: 'default',
  client   types: 'type User {\n  id: ID! @id\n  name: String!\n}\n\n',
  client   dryRun: undefined,
  client   secrets: null,
  client   subscriptions: [],
  client   force: undefined } +2ms
  client { deploy: 
  client    { errors: [],
  client      warnings: [],
  client      migration: { revision: 2, steps: [Array] },
  client      steps: [ [Object], [Object], [Object] ] } } +419ms
 736ms

Changes:

  User (Type)
  + Created type `User`
  + Created field `id` of type `ID!`
  + Created field `name` of type `String!`


Applying changes... (0/3)  client Sending query to cluster local +3ms
  client http://localhost:4466/management +0ms
  client query ($name: String! $stage: String!) {
  client           migrationStatus(name: $name stage: $stage) {
  client             projectId
  client             revision
  client             status
  client             applied
  client             rolledBack
  client             errors
  client           }
  client         }
  client        +0ms
  client { stage: 'default', name: 'default' } +0ms
  client { migrationStatus: 
  client    { rolledBack: 0,
  client      applied: 0,
  client      projectId: 'default@default',
  client      errors: [],
  client      revision: 2,
  client      status: 'IN_PROGRESS' } } +96ms
  client Sending query to cluster local +509ms
  client http://localhost:4466/management +0ms
  client query ($name: String! $stage: String!) {
  client           migrationStatus(name: $name stage: $stage) {
  client             projectId
  client             revision
  client             status
  client             applied
  client             rolledBack
  client             errors
  client           }
  client         }
  client        +0ms
  client { stage: 'default', name: 'default' } +0ms
  client { migrationStatus: 
  client    { rolledBack: 0,
  client      applied: 3,
  client      projectId: 'default@default',
  client      errors: [],
  client      revision: 2,
  client      status: 'SUCCESS' } } +44ms

Applying changes... (3/3)
Applying changes... 1.2s
  client Sending query to cluster local +503ms
  client http://localhost:4466/management +0ms
  client query ($name: String! $stage: String!) {
  client           migrationStatus(name: $name stage: $stage) {
  client             projectId
  client             revision
  client             status
  client             applied
  client             rolledBack
  client             errors
  client           }
  client         }
  client        +0ms
  client { stage: 'default', name: 'default' } +1ms
  client { migrationStatus: 
  client    { rolledBack: 0,
  client      applied: 3,
  client      projectId: 'default@default',
  client      errors: [],
  client      revision: 2,
  client      status: 'SUCCESS' } } +54ms

Generating schema... 32ms
Saving Prisma Client (JavaScript) at /home/d/d/ub/server/generated/prisma-client/

Your Prisma endpoint is live:

  HTTP:  http://localhost:4466
  WS:    ws://localhost:4466

You can view & edit your data here:

  Prisma Admin: http://localhost:4466/_admin

server$ 
```

The file server/src/generated/prisma-client/index.js contains:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var prisma_lib_1 = require("prisma-client-lib");
var typeDefs = require("./prisma-schema").typeDefs;

var models = [
  {
    name: "Link",
    embedded: false
  },
  {
    name: "User",
    embedded: false
  },
  {
    name: "Vote",
    embedded: false
  }
];
exports.Prisma = prisma_lib_1.makePrismaClientClass({
  typeDefs,
  models,
  endpoint: `http://127.0.0.1:4466`
});
exports.prisma = new exports.Prisma();
```

The file server/prisma/prisma.yml contains:
```
# Specifies the HTTP endpoint of your Prisma API.
#endpoint: ''
#endpoint: http://localhost:4466
endpoint: http://127.0.0.1:4466

# Defines your models, each model is mapped to the database as a table.
datamodel: datamodel.prisma

# Specifies the language and directory for the generated Prisma client.
generate:
  - generator: javascript-client
    output: ../src/generated/prisma-client

# Ensures Prisma client is re-generated after a datamodel change.
hooks:
  post-deploy:
    - prisma generate
```

A query in Playground :
```
mutation CreatePrismaLink {
  post(
    description: "Prisma turns your database into a GraphQL API 😎",
    url: "https://www.prismagraphql.com"
  ) {
    id
  }
}
```

returns

```
{
  "data": null,
  "errors": [
    {
      "message": "Variable '$data' cannot be non input type 'LinkCreateInput!'. (line 1, column 18):\nmutation ($data: LinkCreateInput!) {\n                 ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "post"
      ]
    }
  ]
}
```

- Which is another problem, not to solve in this issue.

**Comment by itofficeeu** [comment]
To be reopened in the sense: To correct the tutorial.

**Comment by TasinIshmam** [comment]
Closing because the tutorial has been updated and this issue is no longer relevant.
