### ISSUE TITLE
Error: Must provide Document

### ISSUE THREAD

**Issue by gonzo-32** [howtographql/howtographql#1381]
When following the steps here -> https://www.howtographql.com/graphql-js/1-getting-started/

I get this error at **Testing the GraphQL server** when running the `node src/index.js` :

``hackernews-node node src/index.js
/Users/jlu801/projects/choreo/hackernews-node/node_modules/graphql/jsutils/devAssert.js:12
    throw new Error(message);
    ^

Error: Must provide document.
    at devAssert (/Users/jlu801/projects/choreo/hackernews-node/node_modules/graphql/jsutils/devAssert.js:12:11)
    at assertValidExecutionArguments (/Users/jlu801/projects/choreo/hackernews-node/node_modules/graphql/execution/execute.js:186:40)
    at Object.execute (/Users/jlu801/projects/choreo/hackernews-node/node_modules/graphql/execution/execute.js:107:3)
    at Object.generateSchemaHash (/Users/jlu801/projects/choreo/hackernews-node/node_modules/apollo-server-core/dist/utils/schemaHash.js:15:32)
    at ApolloServer.generateSchemaDerivedData (/Users/jlu801/projects/choreo/hackernews-node/node_modules/apollo-server-core/dist/ApolloServer.js:407:41)
    at new ApolloServerBase (/Users/jlu801/projects/choreo/hackernews-node/node_modules/apollo-server-core/dist/ApolloServer.js:204:41)
    at new ApolloServer (/Users/jlu801/projects/choreo/hackernews-node/node_modules/apollo-server-express/dist/ApolloServer.js:60:9)
    at new ApolloServer (/Users/jlu801/projects/choreo/hackernews-node/node_modules/apollo-server/dist/index.js:34:9)
    at Object.<anonymous> (/Users/jlu801/projects/choreo/hackernews-node/src/index.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)``

**Comment by gonzo-32** [comment]
Looks like it was a dependency issue with graphql reverted to version 14.6.0 and worked fine.

**Comment by TasinIshmam** [comment]
This has been fixed. Closing!
