### ISSUE TITLE
Part 5 (Authentication) issue with SigninUserInput type

### ISSUE THREAD

**Issue by AndreiCalazans** [howtographql/howtographql#178]
For some reason I after writing the both mutations to Sign in and Create User,  when I ran relay-compiler it was throwing an error saying this.

`HINT: pass --watch to keep watching for changes.
Parsed default in 0.12s Writing default
Error: You supplied a GraphQL document with validation errors:
/Users/staff/Documents/andrei/hackernews-react-relay/src/mutations/SigninMutation.js: Unknown type "SigninUserInput". Did you mean "SignupUserInput", "UpdateUserInput", or "DeleteUserInput"?
/Users/staff/Documents/andrei/hackernews-react-relay/src/mutations/CreateUserMutation.js: Unknown type "SigninUserInput". Did you mean "SignupUserInput", "UpdateUserInput", or "DeleteUserInput"?
    at Object.validateOrThrow [as validate] (/Users/staff/Documents/andrei/hackernews-react-relay/node_modules/relay-compiler/bin/relay-compiler:2805:18)
    at convertASTDefinitions (/Users/staff/Documents/andrei/hackernews-react-relay/node_modules/relay-compiler/bin/relay-compiler:1108:28)
    at Object.convertASTDocumentsWithBase (/Users/staff/Documents/andrei/hackernews-react-relay/node_modules/relay-compiler/bin/relay-compiler:1090:11)
    at RelayFileWriter.<anonymous> (/Users/staff/Documents/andrei/hackernews-react-relay/node_modules/relay-compiler/bin/relay-compiler:5317:50)
    at Generator.next (<anonymous>)
    at step (/Users/staff/Documents/andrei/hackernews-react-relay/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/staff/Documents/andrei/hackernews-react-relay/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise (<anonymous>)
    at F (/Users/staff/Documents/andrei/hack`

I noticed that the schema.graphql file was missing the SigninUserInput.

therefore I copied the schema from the end point again using the get-graphql-schema, but it continued with the same problem.

My solution was to copy the schema.graphql from the repo here, which was funny for the fact that it had duplicate types on SignupUserInput.

Well I don`t know what caused this, but the quick fix I found was to just copy the schema.graphql from the repo.

Are there any other way to fix this ? or what might have caused this for me ?

**Comment by nikolasburk** [comment]
Hi @AndreiCalazans, my sincere apologies for the late reply! It seems to me that you were using the schema that that was initially downloaded rather than the one stored here: [https://www.graphqlbin.com/hn-relay-full.graphql](https://www.graphqlbin.com/hn-relay-full.graphql)

There was an instruction in chapter `https://www.howtographql.com/react-relay/2-queries-loading-links/` that explained why that was necessary 🙂 

![image](https://user-images.githubusercontent.com/4058327/36197305-afcfb804-1173-11e8-9245-bd48bd3b7de3.png)

**Comment by sirawat93** [comment]
Hello @nikolasburk, thank you for HowToGraphql tutorial.
But after I follow your React& Relay tutorial, I stuck with Unknown type "SigninUserInput" that I don't know how did you implement it in https://www.graphqlbin.com/hn-relay-full.graphql.  

Can you explain how you implement SigninUserInput input, SigninPayload type please?
