### ISSUE TITLE
elixir tutorial seems to be out of date

### ISSUE THREAD

**Issue by jmarca** [howtographql/howtographql#193]
Following along the tutorial, when I get to the top of this page:  https://www.howtographql.com/graphql-elixir/2-queries/, the text says to modify the file `lib/community/web/schema.ex`

But having followed the instructions so far, I only see the following code tree:

```
lib
├── community
│   ├── application.ex
│   ├── news
│   │   ├── link.ex
│   │   └── news.ex
│   └── repo.ex
├── community.ex
├── community_web
│   ├── channels
│   │   └── user_socket.ex
│   ├── controllers
│   ├── endpoint.ex
│   ├── gettext.ex
│   ├── router.ex
│   └── views
│       ├── error_helpers.ex
│       └── error_view.ex
└── community_web.ex
```

Perhaps the file ``lib/community/web/schema.ex` is something generated by the older phoenix mix tasks?  I'm super new to phoenix/elixir, and am using elixir 1.5.1, phoenix 1.3.0.

Perhaps these schema.ex etc instructions should be for the `lib/community_web/...` path?  On the other hand, the community_web subtree does not exist in the example github project linked in the docs.

I tried just creating the files mentioned and populating them, but then elixir chokes with an error:

```
community$ iex -S mix phx.server
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Compiling 3 files (.ex)
warning: unused alias News
  lib/community/web/schema.ex:4


== Compilation error in file lib/community/web/router.ex ==
** (CompileError) lib/community/web/router.ex:2: module Community.Web is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    lib/community/web/router.ex:2: Community.Web.Router (module)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by jmarca** [comment]
I got the code running (as of the line " Start your server with iex -S mix phx.server ..." ), sticking as close to the howto as possible, in the first commit to my repo here: https://github.com/jmarca/community.git

**Comment by marktani** [comment]
Awesome, could you send in a PR, @jmarca?

**Comment by adamgajzlerowicz** [comment]
@jmarca 
thank you for sharing the repo!

**Comment by jmarca** [comment]
Yeah. I’m better at elixir now, so maybe if/when I go through the tutorial again I’ll have another go at this.
