### ISSUE TITLE
[Backend][Ruby][Chapter][5] Validation failed: User must exist

### ISSUE THREAD

**Issue by conradwt** [howtographql/howtographql#211]
In Backend Ruby Chapter 5, the `ctx[:current_user]` value isn't being set during the execution of the following method:

```ruby
 class Resolvers::CreateLink < GraphQL::Function
    # arguments passed as "args"
    argument :description, !types.String
    argument :url, !types.String

    # return type from the mutation
    type Types::LinkType

    def call(_obj, args, ctx)
      Link.create!(
        description: args[:description],
        url: args[:url],
        user: ctx[:current_user]
      )
    end
 end
```

## Steps to Reproduce
1. create a user

```
mutation {
  createUser (
    name: "test",
    authProvider: {
      email: {
        email: "user@example.com",
        password: "12345678"
      }
    }
  ) {
    id
    email
    name
  }
}
```

1.  sign in the user

```
mutation {
  signInUser(
    email: {
      email: "user@example.com"
      password: "12345678"
    }
   )
   {
      token
      user {
        id
      }
    }
}
```

1. create a link

```
mutation {
  createLink(
    url: "http://example.com",
    description: "My Super Cool Site"
  )
  {
    id
    url
    description
    postedBy {
      id
      name
    }
  }
}
```

1. server response

    Started POST "/graphql" for 127.0.0.1 at 2017-08-26 18:00:04 -0700
    Processing by GraphqlController#execute as */*
      Parameters: {"query"=>"mutation {\n  createLink(\n    url: \"http://example.com\",\n    description: \"My Super Cool Site\"\n  ) \n  {\n    id\n    url\n    description\n    postedBy {\n      id\n      name\n    }\n  }\n}", "variables"=>nil, "graphql"=>{"query"=>"mutation {\n  createLink(\n    url: \"http://example.com\",\n    description: \"My Super Cool Site\"\n  ) \n  {\n    id\n    url\n    description\n    postedBy {\n      id\n      name\n    }\n  }\n}", "variables"=>nil}}
       (0.1ms)  begin transaction
       (0.1ms)  rollback transaction
    Completed 422 Unprocessable Entity in 14ms (ActiveRecord: 0.8ms)
    
    ActiveRecord::RecordInvalid (Validation failed: User must exist):
    
    app/graphql/resolvers/create_link.rb:10:in `call'
    app/controllers/graphql_controller.rb:11:in `execute'

**Comment by conradwt** [comment]
Missed the following line of code within the `sign_in_user.rb`:

```
ctx[:session][:token] = token
```

After adding the above line, things works as expected.  This issue can be closed.
