### ISSUE TITLE
Section 4 Auth

### ISSUE THREAD

**Issue by erichodges** [howtographql/howtographql#414]
After I added the login mutation I'm getting this error when running yarn start:

throw new Error("Field " + field.name.value + ": Couldn't find type " + typeName + " in any of the schemas.");
                    ^

Error: Field feed: Couldn't find type Link in any of the schemas.
    at /Users/erichodges/Documents/Coding/graphcool/hackernew-node/node_modules/graphql-import/dist/definition.js:126:27
    at Array.forEach (<anonymous>)
    at collectNewTypeDefinitions (/Users/erichodges/Documents/Coding/graphcool/hackernew-node/node_modules/graphql-import/dist/definition.js:105:30)
    at Object.completeDefinitionPool (/Users/erichodges/Documents/Coding/graphcool/hackernew-node/node_modules/graphql-import/dist/definition.js:22:41)
    at Object.importSchema (/Users/erichodges/Documents/Coding/graphcool/hackernew-node/node_modules/graphql-import/dist/index.js:85:41)
    at new GraphQLServer (/Users/erichodges/Documents/Coding/graphcool/hackernew-node/node_modules/graphql-yoga/dist/src/index.js:88:45)
    at Object.<anonymous> (/Users/erichodges/Documents/Coding/graphcool/hackernew-node/src/index.js:11:16)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
error Command failed with exit code 1.

**Comment by jhudaz** [comment]
they have made updates to the tutorial, like the conection with the server

**Comment by erichodges** [comment]
Yes, this is why I'm going through the tutorial. It was working up to this point.

**Comment by nikolasburk** [comment]
Thanks a lot for pointing that out @erichodges 🙏 The issue should have been fixed with the latest update to the Node tutorial 🙂

**Comment by lianthompson** [comment]
Is there a solution to this? I'm having the same issue with adding Vote.
