### ISSUE TITLE
react-apollo curl don't work

### ISSUE THREAD

**Issue by maltitco** [howtographql/howtographql#421]
curl https://codeload.github.com/howtographql/graphql-js/tar.gz/starter | tar -xz graphql-js-starter
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     14      0  0:00:01  0:00:01 --:--:--    14
tar: Unrecognized archive format
tar: graphql-js-starter: Not found in archive
tar: Error exit delayed from previous errors.

**Comment by nsamala** [comment]
It looks like that branch, `starter` is missing from the `graph-js` repo. @schickling is this something that just wasn't pushed up? Or should we be using the `master` branch instead?

**Comment by gatezh** [comment]
Is there a way to upvote this issue except of thumbs up reaction?
It is pretty significant I think.

**Comment by nikolasburk** [comment]
Sorry for this and thanks so much for reporting! The issue was that the `curl` was pointing to the wrong repo, it's all fixed now. (Note that you might have to hard refresh your browser to see the updated page).

**Comment by gatezh** [comment]
Hi @nikolasburk !
Thank you for a quick fix!

`curl` command works fine now, it retrieves the server, but server itself doesn't work (unfortunately).

Here's what I get:
```bash
sergii (master) server $ yarn start
yarn run v1.3.2
warning package.json: No license field
$ NODE_ENV=dev node src/index.js
Server is running on http://localhost:4000
TypeError: Cannot read property 'publicClusters' of undefined
    at Environment.<anonymous> (/Users/sergii/Code/Tutorials/hackernews-react-apollo/hackernews-react-apollo/server/node_modules/graphcool-yml/dist/Environment.js:103:39)
    at step (/Users/sergii/Code/Tutorials/hackernews-react-apollo/hackernews-react-apollo/server/node_modules/graphcool-yml/dist/Environment.js:40:23)
    at Object.next (/Users/sergii/Code/Tutorials/hackernews-react-apollo/hackernews-react-apollo/server/node_modules/graphcool-yml/dist/Environment.js:21:53)
    at fulfilled (/Users/sergii/Code/Tutorials/hackernews-react-apollo/hackernews-react-apollo/server/node_modules/graphcool-yml/dist/Environment.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:7934) UnhandledPromiseRejectionWarning: Error: No cluster set. Please set the "cluster" property in your graphcool.yml
    at /Users/sergii/Code/Tutorials/hackernews-react-apollo/hackernews-react-apollo/server/node_modules/graphql-config-extension-graphcool/dist/index.js:137:31
    at step (/Users/sergii/Code/Tutorials/hackernews-react-apollo/hackernews-react-apollo/server/node_modules/graphql-config-extension-graphcool/dist/index.js:40:23)
    at Object.next (/Users/sergii/Code/Tutorials/hackernews-react-apollo/hackernews-react-apollo/server/node_modules/graphql-config-extension-graphcool/dist/index.js:21:53)
    at fulfilled (/Users/sergii/Code/Tutorials/hackernews-react-apollo/hackernews-react-apollo/server/node_modules/graphql-config-extension-graphcool/dist/index.js:12:58)
    at <anonymous>
(node:7934) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7934) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
