### ISSUE TITLE
Stuck in the getting started section

### ISSUE THREAD

**Issue by Daniyal857** [howtographql/howtographql#471]
stuck in the getting started section, after defining the endpoint. I run the below mention command and got the following mention error..
```

yarn install
yarn dev
```
command through error..

```
C:\Users\danial.muhammad\Desktop\ReactJs\react-apollo-master\server\src\index.js:19
    ...req,
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "start" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**server package.json file**
```
{
  "name": "hackernews-graphql-js",
  "scripts": {
    "start": "SET NODE_ENV=dev && node src/index.js",
    "dev": "npm-run-all --parallel start playground",
    "playground": "graphql playground"
  },
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "graphql-yoga": "1.2.0",
    "prisma-binding": "1.4.0"
  },
  "devDependencies": {
    "graphql-cli": "2.12.4",
    "npm-run-all": "4.1.2",
    "prisma-cli": "1.0.0"
  }
}
```
**root package.json file**
```
{
  "name": "hackernews-react-apollo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "apollo-client": "^2.2.0",
    "apollo-client-preset": "^1.0.6",
    "apollo-link": "^1.0.7",
    "apollo-link-ws": "^1.0.4",
    "graphql": "^0.12.3",
    "graphql-tag": "^2.6.1",
    "react": "^16.2.0",
    "react-apollo": "^2.0.4",
    "react-dom": "^16.2.0",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.17",
    "subscriptions-transport-ws": "^0.9.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by atoiv** [comment]
This is probably happening due to an older node.js version. Try updating to a newer version.

Node.js versions [v8.2.1 and older](http://node.green/#ES2018-features-object-rest-spread-properties) don't support [object spread](https://babeljs.io/docs/plugins/transform-object-rest-spread/) out of box.

**Comment by nikolasburk** [comment]
Hey @Daniyal857, thanks a lot for opening the issue! Did @atoiv's suggestion help?

**Comment by orbardugo** [comment]
Hi @nikolasburk ,
I have the same problem, maybe there is any suggestion how to fix it?
how i can update the node.js version?

**Comment by vardhan1990** [comment]
Confirmed it works with node 8.6.0. Thanks @atoiv 
Updated documentation in my fork: https://github.com/vardhan1990/howtographql.git
Can I merge this back? If so, how?

**Comment by geirman** [comment]
FYI: Node 8.2.1 supports object spread if you pass the `--harmony` flag

**Comment by swcarlosrj** [comment]
Thanks @Daniyal857 for opening this issue 😄. Closing this due to inactivity!
