### ISSUE TITLE
Error: Schema must be an instance of GraphQLSchema when running GraphQL playground

### ISSUE THREAD

**Issue by jj-lucas** [howtographql/howtographql#509]
Hejsa,

I can't seem to get the tutorial to work, I'm stuck at the Getting Started step :-/
After running the `curl` to retrieve the server scripts, I followed the next steps described in the guide:

- `yarn prisma deploy`
- Updated the __PRISMA_ENDPOINT__ placeholder
- `yarn install`
- `yarn dev`

At this point, the GraphQL playground is opened, but on the right pane I get the following error: `Unexpected token < in JSON at position 0`

Moreover, the terminal log:
```
Server is running on http://localhost:4000
Serving playground at http://localhost:3000/playground
Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
    at invariant (C:\Users\lugas\workspace\test2\server\node_modules\apollo-server-core\node_modules\graphql\jsutils\invariant.js:18:11)
    at Object.validate (C:\Users\lugas\workspace\test2\server\node_modules\apollo-server-core\node_modules\graphql\validation\validate.js:59:72)
    at doRunQuery (C:\Users\lugas\workspace\test2\server\node_modules\apollo-server-core\dist\runQuery.js:88:38)
    at C:\Users\lugas\workspace\test2\server\node_modules\apollo-server-core\dist\runQuery.js:22:54
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Notes:**
- I'm running Node v8.9.4
- graphql@0.12.3
- During the installation of the server dependencies, I get the following warning
`warning "graphql-playground-middleware-lambda@1.4.2" has unmet peer dependency "aws-lambda@^0.1.2".`. if I manually add that dependency, I still get the same error.

Moreover:

```
C:\Users\lugas\workspace\test2\server>npm list graphql
hackernews-graphql-js@ C:\Users\lugas\workspace\test2\server
+-- graphql-cli@2.14.1
| +-- graphql-cli-prepare@1.4.14
| | +-- graphql-import@0.4.1
| | | `-- graphql@0.12.3
| | `-- graphql-static-binding@0.9.0
| |   `-- graphql@0.12.3
| +-- graphql-config-extension-openapi@1.0.2
| | `-- @kbrandwijk/swagger-to-graphql@1.4.2
| |   `-- graphql@0.12.3
| `-- graphql-playground-middleware-express@1.5.6
|   `-- graphql-playground-html@1.5.4
|     `-- graphql-config@1.1.7
|       `-- graphql@0.12.3
+-- graphql-yoga@1.3.2
| +-- apollo-server-express@1.3.2
| | `-- apollo-server-core@1.3.2
| |   `-- graphql-extensions@0.0.7
| |     `-- graphql@0.11.7  extraneous
| +-- apollo-upload-server@4.0.2
| | `-- graphql@0.11.7  extraneous
| `-- subscriptions-transport-ws@0.9.5
|   `-- graphql@0.11.7  extraneous
+-- prisma@1.2.2
| `-- prisma-cli-core@1.0.13
|   +-- graphql@0.11.7
|   +-- graphql-cli@2.12.4
|   | +-- graphql@0.12.3
|   | +-- graphql-cli-prepare@1.4.11
|   | | +-- graphql-import@0.4.0
|   | | | `-- graphql@0.12.3
|   | | `-- graphql-static-binding@0.8.0
|   | |   `-- graphql@0.12.3
|   | +-- graphql-config@1.1.7
|   | | `-- graphql@0.12.3  deduped
|   | +-- graphql-config-extension-graphcool@1.0.5
|   | | `-- graphql-config@1.1.7
|   | |   `-- graphql@0.12.3
|   | `-- graphql-schema-linter@0.0.27
|   |   `-- graphql@0.10.5
|   `-- graphql-config@1.2.1
|     `-- graphql@0.12.3
`-- prisma-binding@1.5.10
  +-- apollo-link@1.0.7
  | `-- graphql@0.11.7  extraneous
  `-- graphql-tools@2.20.2
    +-- apollo-link@1.1.0
    | `-- graphql@0.13.0  extraneous
    `-- graphql@0.11.7  extraneous

npm ERR! extraneous: graphql@0.11.7 C:\Users\lugas\workspace\test2\server\node_modules\graphql-extensions\node_modules\graphql
npm ERR! extraneous: graphql@0.11.7 C:\Users\lugas\workspace\test2\server\node_modules\apollo-upload-server\node_modules\graphql
npm ERR! extraneous: graphql@0.11.7 C:\Users\lugas\workspace\test2\server\node_modules\subscriptions-transport-ws\node_modules\graphql
npm ERR! extraneous: graphql@0.11.7 C:\Users\lugas\workspace\test2\server\node_modules\prisma-binding\node_modules\apollo-link\node_modules\graphql
npm ERR! extraneous: graphql@0.11.7 C:\Users\lugas\workspace\test2\server\node_modules\prisma-binding\node_modules\graphql-tools\node_modules\graphql
npm ERR! extraneous: graphql@0.13.0 C:\Users\lugas\workspace\test2\server\node_modules\prisma-binding\node_modules\graphql-tools\node_modules\apollo-link\node_modules\graphql
```
Any help is welcome. This has so far been a very well written tutorial, it would be a pity to have to pass because of such an issue :)

**Comment by jj-lucas** [comment]
It looks like the issue was conflicting versions of GraphQL installed in various dependencies´node_modules folders.
In my case I solved it by adding a resolution statement to the server's package.json:
```
...
  "resolutions": {
    "graphql": "0.13.0"
  }
```

Hope this helps other's stumbling on the same issue. If this is a frequent problem, consider adding a note about it in the docs.

**Comment by swcarlosrj** [comment]
Thanks @jj-lucas for opening this issue 😄. Closing this due to inactivity!
