### ISSUE TITLE
React Apollo - Error: Cannot find module 'subscriptions-transport-ws'

### ISSUE THREAD

**Issue by tomdohnal** [howtographql/howtographql#511]
When trying to run the graphql server following the instructions in [https://www.howtographql.com/react-apollo/1-getting-started/](https://www.howtographql.com/react-apollo/1-getting-started/), after running `yarn dev` in the `server` folder I keep getting this error
```
Error: Cannot find module 'subscriptions-transport-ws'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.setPrototypeOf.__proto__ (/home/tom/Code/react/apollo/server/node_modules/apollo-link-ws/lib/bundle.umd.js:2:106)
    at Object.<anonymous> (/home/tom/Code/react/apollo/server/node_modules/apollo-link-ws/lib/bundle.umd.js:5:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
error Command failed with exit code 1.

```

**Comment by edmundo096** [comment]
Seems that `subscriptions-transport-ws` is a peer dependency of  `apollo-link-ws` and thus it wasn't installed.

`npm install` gave this error:
```
npm WARN apollo-client@2.2.5 requires a peer of graphql@^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
```

Not completely sure if this is the best approach since it is a devDependency of `apollo-link-ws`, but installing and saving it made it work: `npm install --save subscriptions-transport-ws`

**Comment by swcarlosrj** [comment]
Thanks @tomdohnal for opening this issue 😄. Closing this due to inactivity!
