### ISSUE TITLE
Named Pipes Error

### ISSUE THREAD

**Issue by PythonDevOp** [howtographql/howtographql#521]
I am trying to follow the backend tutorial for `graphql.js` on the how to graphql website. I am running the following:

- Windows 7, 64 bit
- Node.js version 8.9.4
- Docker Toolbox 18.0.2-ce

When I run `graphql create hackernews-node --boilerplate node-basic`, it asks for the location of where I want to deploy. I select `local`  to create a `local cluster` and it says I need Docker installed.

After making the selection, I get an error:
```
[graphql create] Running boilerplate install script...
Running $ prisma deploy...

? Please choose the cluster you want to deploy "hackernews-node@dev" to

local           Local cluster (requires Docker)
Booting local development cluster !
 !    Windows named pipe error: The system cannot find the file specified.
 !    (code: 2)
 !

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
 !    No cluster set. Please set the "cluster" property in your prisma.yml

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn prisma ENOENT
    at notFoundError (D:\graphQL\yoga\hackernews-node\.install\node_modules\cros
s-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\graphQL\yoga\hackernews-node\.install\node_modules\cross
-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\graphQL\yoga\hackernews-node\.install\node_modul
es\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

```

Once I set the `DEBUG` flag, I get this:

```
Booting local development cluster... !
Error: Windows named pipe error: The system cannot find the file specified. (cod
e: 2)

    at Output.<anonymous> (D:\graphQL\apollo\hackernews-node\node_modules\prisma
-cli-engine\src\Output\index.ts:166:15)
    at step (D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-engine\di
st\Output\index.js:40:23)
    at Object.next (D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-en
gine\dist\Output\index.js:21:53)
    at D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-engine\dist\Out
put\index.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-engi
ne\dist\Output\index.js:11:12)
    at Output.error (D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-e
ngine\dist\Output\index.js:205:16)
    at Function.<anonymous> (D:\graphQL\apollo\hackernews-node\node_modules\pris
ma-cli-engine\src\Command.ts:75:15)
    at step (D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-engine\di
st\Command.js:32:23)
    at Object.throw (D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-e
ngine\dist\Command.js:13:53)
    at rejected (D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-engin
e\dist\Command.js:5:65)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Error: No cluster set. Please set the "cluster" property in your prisma.yml
    at Deploy.<anonymous> (D:\graphQL\apollo\hackernews-node\node_modules\prisma
-cli-core\src\commands\deploy\index.ts:148:13)
    at step (D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-core\dist
\commands\deploy\index.js:42:23)
    at Object.next (D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-co
re\dist\commands\deploy\index.js:23:53)
    at fulfilled (D:\graphQL\apollo\hackernews-node\node_modules\prisma-cli-core
\dist\commands\deploy\index.js:14:58)
    at <anonymous>
Exiting with code: 1
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn prisma ENOENT
    at notFoundError (D:\graphQL\apollo\hackernews-node\.install\node_modules\cr
oss-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\graphQL\apollo\hackernews-node\.install\node_modules\cro
ss-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\graphQL\apollo\hackernews-node\.install\node_mod
ules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

I can't find any reference to this error, or how to fix it. Any help would be greatly appreciated!

**Comment by PythonDevOp** [comment]
Closed and going to reopen in the appropriate repo - https://github.com/howtographql/graphql-js
