### ISSUE TITLE
Dev server fails on missing `commons.js`

### ISSUE THREAD

**Issue by topfunky** [howtographql/howtographql#526]
I'd like to run the howtographql.com development server locally but I'm unable to get it running with the basic `yarn install` and `yarn start`.

### What I did

I cloned the repo and ran `yarn install` and `yarn start` under node `9.5.0` and yarn `1.3.2` on macOS `10.13.3`. I visited http://localhost:8000

### What happened

The browser dev console shows an error where `commons.js` can't be found (404).

In the terminal, I'm also seeing `process._tickDomainCallback` is not a function from `Footer.tsx`

### What I expected

I hoped to be able to run the dev server locally and develop content.

### Other

I also tried running under Docker but ran into dependency problems. What's the best way to run this app in development?

```
FROM node:9.5.0
WORKDIR /app
ADD * /app/
EXPOSE 8000
RUN yarn install
CMD ["yarn", "start"]
```

**Comment by johnny88** [comment]
Hey,

So this seems to be a node 9 issue because when I tried it with node 8 it seems to work. It seems that they problem lies in the deasync dependency being called down the line by babel-traverse. Here is the stack trace:
```
Module build failed: TypeError: /home/johnny/home/howtographql/src/components/home/Footer.tsx: process._tickDomainCallback is not a function                                                                       
    at module.exports.loopWhile (/home/johnny/home/howtographql/node_modules/deasync/index.js:71:11)     
    at PluginPass.enter (/home/johnny/home/howtographql/node_modules/styled-jsx-postcss/dist/babel.js:109:34)                                                                                                      
    at newFn (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/visitors.js:276:21)         
    at NodePath._call (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/path/context.js:76:18)                                                                                                       
    at NodePath.call (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/path/context.js:48:17)                                                                                                        
    at NodePath.visit (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/path/context.js:105:12)                                                                                                      
    at TraversalContext.visitQueue (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/context.js:150:16)                                                                                              
    at TraversalContext.visitSingle (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/context.js:108:19)                                                                                             
    at TraversalContext.visit (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/context.js:192:19)                                                                                                   
    at Function.traverse.node (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/index.js:114:17)                                                                                                     
    at NodePath.visit (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/path/context.js:115:19)                                                                                                      
    at TraversalContext.visitQueue (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/context.js:150:16)                                                                                              
    at TraversalContext.visitQueue (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/context.js:156:21)                                                                                              
    at TraversalContext.visitMultiple (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/context.js:103:17)                                                                                           
    at TraversalContext.visit (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/context.js:190:19)                                                                                                   
    at Function.traverse.node (/home/johnny/home/howtographql/node_modules/babel-traverse/lib/index.js:114:17) 
```
It is fixed in the library so we should just need to update the dependency but unfortunately it's a dependency of a dependency... not so simple. Here is the deasync library's associated ticket: `https://github.com/abbr/deasync/issues/89`.

This is the repo that uses it in the howtographql project `https://github.com/timsuchanek/styled-jsx-postcss#build3`. We'll just need them to update deasync to 0.1.12.

**Comment by swcarlosrj** [comment]
Thanks @topfunky for opening this issue 😄Closing this due to inactivity!
