### ISSUE TITLE
(React + Apollo) Failure on "yarn dev"

### ISSUE THREAD

**Issue by mozark24** [howtographql/howtographql#606]
Proceeding to the "yarn dev" step results in the following error the command line:

```
C:\Users\Chris\hackernews-react-apollo\server>yarn dev
yarn run v1.5.1
warning package.json: No license field
$ npm-run-all --parallel start playground
warning package.json: No license field
warning package.json: No license field
$ node src/index.js
$ graphql playground
C:\Users\Chris\hackernews-react-apollo\server\src\index.js:19
    ...req,
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c node src/index.js
Directory: C:\\Users\\Chris\\hackernews-react-apollo\\server
Output:
".
```
And this error trace in the generated yarn-error.log:
```
Trace: 
  Error: Command failed.
  Exit code: 3221225786
  Command: C:\WINDOWS\system32\cmd.exe
  Arguments: /d /s /c react-scripts start
  Directory: C:\Users\Chris\hackernews-react-apollo
  Output:
  
      at ProcessTermError.MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:186:110)
      at new ProcessTermError (C:\Program Files (x86)\Yarn\lib\cli.js:226:113)
      at ChildProcess.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:30281:17)
      at emitTwo (events.js:125:13)
      at ChildProcess.emit (events.js:213:7)
      at maybeClose (internal/child_process.js:921:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```
Yarn 1.5.1
Node 8.2.1
Win 10 x64

I am uncertain where the issue may be.

**Comment by mozark24** [comment]
I updated my NodeJS to 8.11.1 and was able to proceed.

**Comment by nikolasburk** [comment]
Thanks for the update, closing this issue since it seems it was related to your Node version 🙌
