### ISSUE TITLE
Compilation failed with `process._tickDomainCallback is not a function`

### ISSUE THREAD

**Issue by harishzen** [howtographql/howtographql#624]
After doing a yarn start. 
The compilation fails with this error:

 ERROR  Failed to compile with 9 errors                                                                                                                                   17:28:34

 error  in ./src/templates/Tutorials.tsx
```
Module build failed: TypeError: /Users/harish/work/projects/howtographql/src/templates/Tutorials.tsx: process._tickDomainCallback is not a function
    at module.exports.loopWhile (/Users/harish/work/projects/howtographql/node_modules/styled-jsx-postcss/node_modules/deasync/index.js:71:11)
    at PluginPass.enter (/Users/harish/work/projects/howtographql/node_modules/styled-jsx-postcss/dist/babel.js:109:34)
    at newFn (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitQueue (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/context.js:156:21)
    at TraversalContext.visitMultiple (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/harish/work/projects/howtographql/node_modules/babel-traverse/lib/index.js:114:17)
```

Any clues on how to go about fixing this?

**Comment by swcarlosrj** [comment]
Thanks @harishzen for opening this issue 😄. it should be fixed. Closing this!
