### ISSUE TITLE
make project more modular, "Authentication" part of tutorial

### ISSUE THREAD

**Issue by mjaracz** [howtographql/howtographql#742]
Thanks for greate tutorial, is awsome.

I have a small problem that I can not understand. I'm posting belowe, my error, from console  where I try to start my node server:

```
C:\Users\Weronika\Documents\michal\first-graphgl-server\src\resolvers\Query.js:1
(function (exports, require, module, __filename, __dirname) { ��f
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Weronika\Documents\michal\first-graphgl-server\src\index.js:4:15)

```

and below my pieces of code:

first query file 
```
function feed(parent, args, context, info) {
  return context.db.query.links({}, info)
}

module.exports = {
  feed,
}
```

next index file where I keep instantiate of node server

```
const { GraphQLServer } = require('graphql-yoga');
const { Prisma } = require('prisma-binding');

const Query = require('./resolvers/Query')
const Mutation = require('./resolvers/Mutation')
const AuthPayload = require('./resolvers/AuthPayload')

const resolvers = { 
  Query,
  Mutation,
  AuthPayload
}

const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  context: req => ({
    ...req,
    db: new Prisma({
      typeDefs: 'src/generated/prisma.graphql',
      endpoint: 'https://eu1.prisma.sh/mjaracz-b561d8/example/dev',
      secret: 'mysecret123',
      debug: true,
    }),
  }),
})
server.start(() => console.log(`Server is running on the https://localhost:4000`))
```

Do you have some ideas ??

**Comment by swcarlosrj** [comment]
Thanks @mjaracz for opening this issue 😄. it should be fixed. Closing this!
