### ISSUE TITLE
Section 5 RealTime GraphQL Subscriptions

### ISSUE THREAD

**Issue by lianthompson** [howtographql/howtographql#754]
After adding the code for the voting feature I get this error:

throw new Error("Field " + node.name.value + ": Couldn't find type " + nodeTypeName + " in any of the schemas.");
                ^

Error: Field vote: Couldn't find type Vote in any of the schemas.
    at collectNode (/Users/lianthompson/Desktop/hackernews-node/node_modules/graphql-import/dist/definition.js:101:23)
    at /Users/lianthompson/Desktop/hackernews-node/node_modules/graphql-import/dist/definition.js:87:13
    at Array.forEach (<anonymous>)
    at collectNewTypeDefinitions (/Users/lianthompson/Desktop/hackernews-node/node_modules/graphql-import/dist/definition.js:86:30)
    at Object.completeDefinitionPool (/Users/lianthompson/Desktop/hackernews-node/node_modules/graphql-import/dist/definition.js:23:41)
    at Object.importSchema (/Users/lianthompson/Desktop/hackernews-node/node_modules/graphql-import/dist/index.js:87:41)
    at mergeTypeDefs (/Users/lianthompson/Desktop/hackernews-node/node_modules/graphql-yoga/dist/index.js:401:37)
    at new GraphQLServer (/Users/lianthompson/Desktop/hackernews-node/node_modules/graphql-yoga/dist/index.js:91:34)
    at Object.<anonymous> (/Users/lianthompson/Desktop/hackernews-node/src/index.js:19:16)
    at Module._compile (module.js:652:30)

**Comment by r00bal** [comment]
Hi @lianthompson, have found the solution to above? I am during the tutorial, having the same issue
