### ISSUE TITLE
java.lang.IllegalStateException[Exception in thread "Thread-2"] java.lang.NumberFormatException: For input string: "36m"

### ISSUE THREAD

**Issue by vishrantgupta** [howtographql/howtographql#755]
```
>java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

`mvn -X clean install jetty:run`

```
[DEjava.lang.IllegalStateException[DEException in thread "Thread-2" BUG]java.lang.NumberFormatException: For input string: "36m"
Sca     at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)n
n       at java.lang.Integer.parseInt(Integer.java:580)
i       at java.lang.Integer.<init>(Integer.java:867)ng
        at org.fusesource.jansi.AnsiPrintStream.filter(AnsiPrintStream.java:129)
c       at org.fusesource.jansi.FilterPrintStream.write(FilterPrintStream.java:97)l
a       at org.fusesource.jansi.FilterPrintStream.write(FilterPrintStream.java:107)s
s       at org.fusesource.jansi.FilterPrintStream.print(FilterPrintStream.java:156)
        at org.slf4j.impl.MavenSimpleLogger.writeThrowable(MavenSimpleLogger.java:69)
f       at org.slf4j.impl.SimpleLogger.write(SimpleLogger.java:319)r
o       at org.slf4j.impl.SimpleLogger.log(SimpleLogger.java:295)m
        at org.slf4j.impl.SimpleLogger.debug(SimpleLogger.java:467)j
a       at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:105)r
        at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:100)j
a       at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:150)r
```

**Comment by swcarlosrj** [comment]
Thanks @vishrantgupta for opening this issue 😄. Closing this due to innactivity!
