### ISSUE TITLE
Incorrect schema.graphql path on 3-a-simple-mutation.md

### ISSUE THREAD

**Issue by letsila** [howtographql/howtographql#876]
I just ran through the nodeJS/graphQL tutorial and got an error while specifying the path for schema.graphql which should be `./src/schema.graphql` instead of `./schema.graphql`.

```bash
Error: No schema found for path: /Users/user/Sites/hackernews-node/schema.graphql
    at mergeTypeDefs (/Users/user/Sites/hackernews-node/node_modules/graphql-yoga/dist/index.js:418:23)
    at new GraphQLServer (/Users/user/Sites/hackernews-node/node_modules/graphql-yoga/dist/index.js:95:34)
    at Object.<anonymous> (/Users/user/Sites/hackernews-node/src/index.js:29:16)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
```

This is actually caused by this [commit](https://github.com/howtographql/howtographql/commit/39fd79db51fea43ccdd69952fa0a84c660b13e05) in #821 PR which deleted the `./src` from the path string.

A similar [PR](https://github.com/howtographql/howtographql/pull/664) #664 has already been refused which attempted to remove `./src` from the `schema.graphql` path.

**Comment by swcarlosrj** [comment]
Thanks @letsila for opening this issue 😄. It's already fixed, just we're waiting to be released!
