### ISSUE TITLE
Issue building locally

### ISSUE THREAD

**Issue by CrashyBang** [howtographql/howtographql#954]
I am trying to build locally and receiving the following error:

```
[ { GraphQLError: Cannot query field "allMarkdownRemark" on type "RootQueryType".
      at Object.Field (howtographql/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:65:31)
      at Object.enter (howtographql/node_modules/graphql/language/visitor.js:295:29)
      at Object.enter (howtographql/node_modules/graphql/language/visitor.js:337:25)
      at visit (howtographql/node_modules/graphql/language/visitor.js:227:26)
      at visitUsingRules (howtographql/node_modules/graphql/validation/validate.js:75:22)
      at validate (howtographql/node_modules/graphql/validation/validate.js:60:10)
      at howtographql/node_modules/graphql/graphql.js:69:51
      at Promise._execute (howtographql/node_modules/bluebird/js/release/debuggability.js:313:9)
      at Promise._resolveFromExecutor (howtographql/node_modules/bluebird/js/release/promise.js:483:18)
      at new Promise (howtographql/node_modules/bluebird/js/release/promise.js:79:10)
      at graphqlImpl (howtographql/node_modules/graphql/graphql.js:59:10)
      at graphql (howtographql/node_modules/graphql/graphql.js:48:227)
      at graphqlRunner (howtographql/node_modules/gatsby/dist/bootstrap/index.js:315:22)
      at Promise (howtographql/gatsby-node.js:37:7)
      at Promise._execute (howtographql/node_modules/bluebird/js/release/debuggability.js:313:9)
      at Promise._resolveFromExecutor (howtographql/node_modules/bluebird/js/release/promise.js:483:18)
    message:
     'Cannot query field "allMarkdownRemark" on type "RootQueryType".',
    locations: [ [Object] ],
    path: undefined } ]

A plugin returned an error

TypeError: Cannot read property 'allMarkdownRemark' of undefined
    at graphql.then.result (howtographql/gatsby-node.js:61:21)
    at tryCatcher (howtographql/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (howtographql/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (howtographql/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (howtographql/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (howtographql/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (howtographql/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (howtographql/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (howtographql/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)
error Command failed with exit code 1.
```

I can see that the issues is occurring here (`gatsby-node.js`):

```js
exports.createPages = ({ graphql, boundActionCreators }) => {
  const { createPage } = boundActionCreators

  return new Promise((resolve, reject) => {
    const pages = []
    const tutorials = path.resolve('src/templates/Tutorials.tsx')
    // Query for all markdown "nodes" and for the slug we previously created.
    resolve(
      graphql(
        `{
          allMarkdownRemark {
            edges {
              node {
                frontmatter {
                  title
                }
                fields {
                  slug
                }
                excerpt(pruneLength: 1000)
              }
            }
          }
        }
      `
      ).then(result => {
        if (result.errors) {
          console.log(result.errors)
          reject(result.errors)
        }

        // Create blog posts pages.
        result.data.allMarkdownRemark.edges.forEach(edge => {
          createPage({
            path: edge.node.fields.slug, // required
            component: tutorials,
            context: {
              slug: edge.node.fields.slug,
            },
          })
        })

        if (process.env.NODE_ENV === 'production') {
          try {
            syncToAlgolia(result.data)
          } catch (e) {
            console.log('Warning: Algolia Error')
          }
        }

        return
      })
    )
  })
}
```

I found these related issues [#3150](https://github.com/gatsbyjs/gatsby/issues/3150) & [#2150](https://github.com/gatsbyjs/gatsby/issues/2150) but they didn't do much to help.

I have not modified the files at all, I did remove the `package-lock.json` and the `yarn.lock` and re-ran `yarn install` and then manually matched all the versions to those in the current repo (this was to do with issues I was getting related to `node-gyp` and it resolved those issues).

I would like to fix this issue and submit a PR with the updated lock file which I hope will fix any issues for others trying to get started.

**Comment by Travisg25** [comment]
Did you ever find a solution to this? I am running into the same issue rn.

**Comment by CrashyBang** [comment]
@Travisg25 no I have not found a solution yet, I haven't look at this for a while though.

**Comment by amir-yaghoubi** [comment]
I have the same issue, right now all of `gatsby-plugin-*:next` does not exists anymore, so I have to replace them with the corresponding version in `yarn.lock` and then I ran `yarn install`, in the end `yarn start` and I got this error, any update on how to resolve this issue?
